# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_bookshop

on:
  workflow_dispatch:
  schedule:
    - cron: '1 8,12,18 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: bookshop
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b  master https://github.com/SallyU/fuidvsfjkd.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【口袋书店】'
        run: |
          cd ~/scripts
          sed -i 's/d658e590b4bd4cccb19ee1b205506865/217150b921ed45b4a7fc9cf004f52caf/' jd_bookshop.js
          sed -i 's/1fc4dc2e6e7345b18edbe24abb54a7d5/54dcb9bf01ce4c7cbbc943ecc36b2961/' jd_bookshop.js
          node jd_bookshop.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          PURCHASE_SHOPS: ${{ secrets.PURCHASE_SHOPS }}
