# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jd_immortal 神仙书院

on:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'
  watch:
        types: started
  repository_dispatch:
    types: jd_immortal
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          wget -P ~/scripts https://raw.githubusercontent.com/wheatwee/crazyjoy/main/jd_immortal.js
          wget -P ~/scripts https://raw.githubusercontent.com/SallyU/fuidvsfjkd/master/jdCookie.js
          wget -P ~/scripts https://raw.githubusercontent.com/SallyU/fuidvsfjkd/master/sendNotify.js
          wget -P ~/scripts https://raw.githubusercontent.com/SallyU/fuidvsfjkd/master/package.json
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} 
      - name: '运行 【神仙书院】'
        run: | 
          cd ~/scripts
          npm install 
          node jd_immortal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
